# Window Rules

# Example floating windows
windowrule = float, file_progress
windowrule = float, confirm
windowrule = float, dialog
windowrule = float, download
windowrule = float, notification
windowrule = float, splash
windowrule = float, toolbar
windowrule = float, rofi
windowrule = float, wlogout

# Picture in picture
windowrulev2 = float, title:Picture-in-picture
windowrulev2 = pin, title:Picture-in-picture
