# /* ---- 💫 Min Developer: Stephen Kibira | Codename: codecrafter 💫 ---- */  #
# Commands and Apps to be executed at launch
$livewallpaper=""
exec-once = $HOME/.config/hypr/scripts/ApplyWallpaper.sh
#exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper
